version: '3.8'
services:
  api-server:
    build: ./
    entrypoint: ['npm', 'run', 'start:dev']
    # env_file: ./config/config.env
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - '5432:5432'
    networks:
      app_net:
        ipv4_address: 192.168.0.2
    volumes:
      - postgres-data:/data/db
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
    networks:
      app_net:
        ipv4_address: 192.168.0.3
    volumes:
      - pg-admin-data:/data/pgadmin

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: '192.168.0.0/24'
          gateway: 192.168.0.1

volumes:
  postgres-data:
    driver: local
  pg-admin-data:
    driver: local
